In [2]:
#Task 1
import numpy as np
np.full([3,3], 55)

array([[55, 55, 55],
       [55, 55, 55],
       [55, 55, 55]])

In [3]:
#Task 2
#1)
#정배
arr=np.zeros(10)
arr[4]=1
print(arr)
# a=np.identity(10)
# print(a[4,:])

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [4]:
#2) 
np.arange(9, -1, -1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [6]:
#3)
a3=np.arange(9)
a3=a3.reshape(3,3)
print(a3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
#Task 3
a=np.zeros((5,5))
a[:,:]=np.arange(0,5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [8]:
#Task 4
a=np.zeros((2,3,4), int)
a[:,1,:]=[2,2,2,2]
print(a)

[[[0 0 0 0]
  [2 2 2 2]
  [0 0 0 0]]

 [[0 0 0 0]
  [2 2 2 2]
  [0 0 0 0]]]


In [11]:
#Task 5
a=np.zeros((8,8), int)
a[::2]=[0,1,0,1,0,1,0,1]
a[1::2]=[1,0,1,0,1,0,1,0]
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [12]:
#Task 6
array=np.array([
    [3,2,8],
    [4,12,34],
    [23,12,67]
])
newRow=np.array([2,1,8])
arr=np.vstack((array, newRow))
print(arr)

[[ 3  2  8]
 [ 4 12 34]
 [23 12 67]
 [ 2  1  8]]


In [13]:
#Task 7
#1) 
A = np.ones(3)*1
B = np.ones(3)*2

np.multiply(np.add(A,B),np.divide(-A, 2))
# np.array((A+B)*(-A/2))
# print((A+B)*(-A/2))

array([-1.5, -1.5, -1.5])

In [14]:
#2)
list = [
    np.array([3, 2, 8, 9]),
    np.array([4, 12, 34, 25, 78]),
    np.array([23, 12, 67])
]
print(np.mean(list[0]))
print(np.mean(list[1]))
print(np.mean(list[2]))

5.5
30.6
34.0
